#
# Module manifest for module 'NewManifest'
#
# Generated by: Jakku Labs
#
# Generated on: 12/08/2016
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'PowervRO.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # ID used to uniquely identify this module
    GUID              = '1f3a9882-40ac-4b4e-9950-b2526da895d7'

    # Author of this module
    Author            = 'Jakku Labs'

    # Company or vendor of this module
    CompanyName       = 'Jakku Labs'

    # Copyright statement for this module
    Copyright         = '(c) 2016 Jakku Labs. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'PowerShell Module for Managing VMware vRealize Orchestrator'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = @('Add-vROActionPermission','Add-vROCategoryPermission','Add-vROConfigurationElementPermission','Add-vROPackagePermission','Add-vROResourceElementPermission','Add-vROWorkflowPermission','Connect-vROServer','Disconnect-vROServer','Export-vROAction','Export-vROConfigurationElement','Export-vROPackage','Export-vROPlugin','Export-vROResourceElement','Export-vROWorkflow','Export-vROWorkflowIcon','Export-vROWorkflowSchema','Get-vROAction','Get-vROActionPermission','Get-vROAPIEndpoint','Get-vROCategory','Get-vROCategoryPermission','Get-vROConfigurationElement','Get-vROConfigurationElementPermission','Get-vROPackage','Get-vROPackagePermission','Get-vROPlugin','Get-vROResourceElement','Get-vROResourceElementPermission','Get-vROUser','Get-vROVersion','Get-vROWorkflow','Get-vROWorkflowExecution','Get-vROWorkflowExecutionResult','Get-vROWorkflowExecutionState','Get-vROWorkflowPermission','Import-vROAction','Import-vROConfigurationElement','Import-vROPackage','Import-vROPlugin','Import-vROResourceElement','Import-vROWorkflow','Invoke-vROAction','Invoke-vRORestMethod','Invoke-vROWorkflow','New-vROCategory','New-vROParameterDefinition','Remove-vROAction','Remove-vROActionPermission','Remove-vROCategory','Remove-vROCategoryPermission','Remove-vROConfigurationElement','Remove-vROConfigurationElementPermission','Remove-vROPackage','Remove-vROPackagePermission','Remove-vROResourceElement','Remove-vROResourceElementPermission','Remove-vROWorkflow','Remove-vROWorkflowPermission','Set-vROPluginState')

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Orchestrator', 'VMware', 'vRO', 'vCO')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/jakkulabs/PowervRO/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/jakkulabs/PowervRO'

            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/jakkulabs/PowervRO/master/media/PowervRO-icon.png'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://raw.githubusercontent.com/jakkulabs/PowervRO/master/docs/CHANGELOG.md'

            # External dependent modules of this module
            # ExternalModuleDependencies = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

